Don't specify explicit version for dev-dependencies (#258)
* Don't specify explicit version for dev-dependencies

alice@pop-os:~/Documents/Code/taffy$ cargo publish --dry-run
    Updating crates.io index
   Packaging taffy v0.2.0 (/home/alice/Documents/Code/taffy)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `taffy = "^0.2.0"`
  candidate versions found which didn't match: 0.1.0
  location searched: crates.io index
  required by package `taffy v0.2.0 (/home/alice/Documents/Code/taffy)`

* Clean up cargo-deny warnings

* Bypass duplicate detection for taffy itself

* Remove stale duplicate allow